// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TrxObj is an autogenerated mock type for the TrxObj type
type TrxObj struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (_m *TrxObj) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rollback provides a mock function with given fields:
func (_m *TrxObj) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTrxObj creates a new instance of TrxObj. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrxObj(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrxObj {
	mock := &TrxObj{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
